services:
  users-service:
    build: users/.
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_NAME=spring-microservices-users
      - DB_USER=amirkhan
      - DB_PASSWORD=123
      - DB_HOST=postgres-service-users

  posts-service:
    build: posts/.
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_NAME=spring-microservices-posts
      - DB_USER=amirkhan
      - DB_PASSWORD=123
      - DB_HOST=postgres-service-posts
  postgres-service-users:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=spring-microservices-users
      - POSTGRES_USER=amirkhan
      - POSTGRES_PASSWORD=123

  postgres-service-posts:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=spring-microservices-posts
      - POSTGRES_USER=amirkhan
      - POSTGRES_PASSWORD=123

  api-gateway-service:
    build: api-gateway/.
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker